/**
 * @file matlabExport.ts
 * @description Utility to generate and download a MATLAB (.m) script 
 * for system validation based on the AI-designed compensator.
 * 
 * @authors Mattia Franchini & Michele Bisignano
 * @version 1.0.0
 */

import type { Compensator, SystemInput } from '../types/ControlSystems';

/**
 * Generates a formatted MATLAB script string.
 * @param input - The original plant G(s) coefficients.
 * @param comp - The optimized compensator results.
 * @returns A string containing the MATLAB source code.
 */
export const generateMatlabScript = (input: SystemInput, comp: Compensator): string => {
    const timestamp = new Date().toLocaleString();
    
    // Format arrays for MATLAB syntax: [1, 2, 10] -> [1 2 10]
    const numStr = `[${input.numerator.join(' ')}]`;
    const denStr = `[${input.denominator.join(' ')}]`;

    return `% --- SmartBode Tuner MATLAB Validation Script ---
% Generated by: Mattia Franchini & Michele Bisignano
% Date: ${timestamp}

clear all; close all; clc;
fprintf('Initializing SmartBode Design Validation...\\n');

%% 1. Plant Definition G(s)
% Defined from user input: Num=${numStr}, Den=${denStr}
G = tf(${numStr}, ${denStr});

%% 2. Compensator Definition C(s)
% Architecture: C(s) = K * (1 + Ts) / (1 + alpha*Ts)
% AI Classification: ${comp.type}
K = ${comp.K.toFixed(6)};
T = ${comp.T.toFixed(6)};
alpha = ${comp.alpha.toFixed(6)};

s = tf('s');
C = K * (1 + T*s) / (1 + (alpha * T)*s);

%% 3. Open-Loop System L(s)
L = C * G;

%% 4. Closed-Loop System W(s) (Unity Feedback)
W = feedback(L, 1);

%% 5. Graphical Analysis
figure('Name', 'SmartBode: Frequency Domain Analysis', 'NumberTitle', 'off');
margin(L); % Shows Phase and Gain margins on Bode Plot
grid on;

figure('Name', 'SmartBode: Time Domain Analysis', 'NumberTitle', 'off');
step(W); % Closed-loop step response
title('Closed-Loop Step Response');
grid on;

% Output final margins to console
[gm, pm, wg, wp] = margin(L);
fprintf('\\n--- Validation Results ---\\n');
fprintf('Achieved Phase Margin: %.2f degrees at %.2f rad/s\\n', pm, wp);
fprintf('Achieved Gain Margin: %.2f dB at %.2f rad/s\\n', 20*log10(gm), wg);
`;
};

/**
 * Triggers a browser download of the generated .m script.
 */
export const downloadMatlabFile = (input: SystemInput, comp: Compensator) => {
    const scriptContent = generateMatlabScript(input, comp);
    const blob = new Blob([scriptContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    link.download = `smartbode_design_${Date.now()}.m`;
    document.body.appendChild(link);
    link.click();
    
    // Cleanup to prevent memory leaks
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};